### ISSUE TITLE
ERROR: 

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#18]
- Launch Explorer
- Search Magnification:10
- Select the first two microscopes
- Click compare
- Open Magnification>Objective
- Open FluorescenceLightSurce
- Click on first item
- Click on second item >>>> CRASH

Happens also when second item is clicked on first
Happens also when a search is performed with two items

-----
**ERROR**
componentsView.js:282 Uncaught TypeError: Cannot read properties of undefined (reading 'IlluminationPower')
    at eval (componentsView.js:282:92)
    at Array.forEach (<anonymous>)
    at eval (componentsView.js:278:22)
    at Array.forEach (<anonymous>)
    at eval (componentsView.js:276:41)
    at Array.forEach (<anonymous>)
    at ComponentsView.createSubRows (componentsView.js:269:31)
    at eval (componentsView.js:332:32)
    at Array.forEach (<anonymous>)
    at eval (componentsView.js:323:17)
/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.4-b1/2-0-4-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20085 The above error occurred in the <ComponentsView> component:

    at ComponentsView (webpack://MicroMetaAppElectron/./node_modules/micro-meta-explorer/es/components/componentsView.js?:151:5)
    at div
    at div
    at MicroMetaExplorerContainer (webpack://MicroMetaAppElectron/./node_modules/micro-meta-explorer/es/app.js?:961:5)
    at MicroMetaExplorer (webpack://MicroMetaAppElectron/./node_modules/micro-meta-explorer/es/app.js?:48:5)
    at div
    at MicroMetaAppElectronComponent (webpack://MicroMetaAppElectron/./src/app.js?:352:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.4-b1/2-0-4-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20085
/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.4-b1/2-0-4-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11340 Uncaught TypeError: Cannot read properties of undefined (reading 'IlluminationPower')
    at eval (componentsView.js:282:92)
    at Array.forEach (<anonymous>)
    at eval (componentsView.js:278:22)
    at Array.forEach (<anonymous>)
    at eval (componentsView.js:276:41)
    at Array.forEach (<anonymous>)
    at ComponentsView.createSubRows (componentsView.js:269:31)
    at eval (componentsView.js:332:32)
    at Array.forEach (<anonymous>)
    at eval (componentsView.js:323:17)
/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.4-b1/2-0-4-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at MicroMetaAppElectronComponent (webpack://MicroMetaAppElectron/./src/app.js?:352:5)
printWarning @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.4-b1/2-0-4-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:67

**Comment by strambc** [comment]
Due to the presence of Sub-Elements of different number (One Laser has 2 IlluminationWLRange and the other has 1)
